### PR TITLE
Add support for code block line number transparency

### LINKED ISSUE #343: 建议代码框左侧行号不要透明
发现代码框在不折行的情况下，将代码横向移动会和行号重叠，体验不好，建议行号单独一列
截图

### PR DESCRIPTION
**Pull request by yzxoi**
fix #343

### CODE REVIEW

**Comment by solstice23** [comment]
it is better to add a class to the highlight block instead of css injection
example https://github.com/solstice23/argon-theme/blob/509909e819c4c6d7772d171da6daa8e02d43809e/argontheme.js#L2360

**Comment by yzxoi** [comment]
The specific loading of hljs comes after document.ready(), which means we can't quickly and efficiently add classes to it.

**Comment by solstice23** [comment]
https://github.com/solstice23/argon-theme/blob/509909e819c4c6d7772d171da6daa8e02d43809e/argontheme.js#L2360

**Comment by yzxoi** [comment]
I mean ln-numbers inside hljs.The father <pre> still loads fine.

**Pull request merged**
